/*
 Magnific Popup - v0.9.9 - 2014-09-06
 http://dimsemenov.com/plugins/magnific-popup/
 Copyright (c) 2014 Dmitry Semenov; */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(e,a,n){e instanceof String&&(e=String(e));for(var h=e.length,g=0;g<h;g++){var u=e[g];if(a.call(n,u,g,e))return{i:g,v:u}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,a,n){e!=Array.prototype&&e!=Object.prototype&&(e[a]=n.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,a,n,h){if(a){n=$jscomp.global;e=e.split(".");for(h=0;h<e.length-1;h++){var g=e[h];g in n||(n[g]={});n=n[g]}e=e[e.length-1];h=n[e];a=a(h);a!=h&&null!=a&&$jscomp.defineProperty(n,e,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6-impl","es3");
(function(e){var a,n,h,g,u,v,G,x=function(){},A=!!window.jQuery,r=e(window),k=function(b,c){a.ev.on("mfp"+b+".mfp",c)},m=function(a,c,d,f){var b=document.createElement("div");return b.className="mfp-"+a,d&&(b.innerHTML=d),f?c&&c.appendChild(b):(b=e(b),c&&b.appendTo(c)),b},l=function(b,c){a.ev.triggerHandler("mfp"+b,c);a.st.callbacks&&(b=b.charAt(0).toLowerCase()+b.slice(1),a.st.callbacks[b]&&a.st.callbacks[b].apply(a,e.isArray(c)?c:[c]))},B=function(b){return b===G&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=
e(a.st.closeMarkup.replace("%title%",a.st.tClose)),G=b),a.currTemplate.closeBtn},C=function(){e.magnificPopup.instance||(a=new x,a.init(),e.magnificPopup.instance=a)},K=function(){var a=document.createElement("p").style,c=["ms","O","Moz","Webkit"];if(void 0!==a.transition)return!0;for(;c.length;)if(c.pop()+"Transition"in a)return!0;return!1};x.prototype={constructor:x,init:function(){var b=navigator.appVersion;a.isIE7=-1!==b.indexOf("MSIE 7.");a.isIE8=-1!==b.indexOf("MSIE 8.");a.isLowIE=a.isIE7||
a.isIE8;a.isAndroid=/android/gi.test(b);a.isIOS=/iphone|ipad|ipod/gi.test(b);a.supportsTransition=K();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);g=e(document);a.popupsCache={}},open:function(b){h||(h=e(document.body));var c;if(!1===b.isObj){a.items=b.items.toArray();a.index=0;var d,f=b.items;for(c=0;f.length>c;c++)if(d=f[c],d.parsed&&(d=d.el[0]),d===b.el[0]){a.index=c;break}}else a.items=e.isArray(b.items)?
b.items:[b.items],a.index=b.index||0;if(a.isOpen)return a.updateItemHTML(),void 0;a.types=[];v="";a.ev=b.mainEl&&b.mainEl.length?b.mainEl.eq(0):g;b.key?(a.popupsCache[b.key]||(a.popupsCache[b.key]={}),a.currTemplate=a.popupsCache[b.key]):a.currTemplate={};a.st=e.extend(!0,{},e.magnificPopup.defaults,b);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=!1,a.st.closeOnBgClick=!1,a.st.showCloseBtn=!1,a.st.enableEscapeKey=!1);
a.bgOverlay||(a.bgOverlay=m("bg").on("click.mfp",function(){a.close()}),a.wrap=m("wrap").attr("tabindex",-1).on("click.mfp",function(b){a._checkIfClose(b.target)&&a.close()}),a.container=m("container",a.wrap));a.contentContainer=m("content");a.st.preloader&&(a.preloader=m("preloader",a.container,a.st.tLoading));d=e.magnificPopup.modules;for(c=0;d.length>c;c++)f=d[c],f=f.charAt(0).toUpperCase()+f.slice(1),a["init"+f].call(a);l("BeforeOpen");a.st.showCloseBtn&&(a.st.closeBtnInside?(k("MarkupParse",
function(a,b,c,d){c.close_replaceWith=B(d.type)}),v+=" mfp-close-btn-in"):a.wrap.append(B()));a.st.alignTop&&(v+=" mfp-align-top");a.fixedContentPos?a.wrap.css({overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}):a.wrap.css({top:r.scrollTop(),position:"absolute"});(!1===a.st.fixedBgPos||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:g.height(),position:"absolute"});a.st.enableEscapeKey&&g.on("keyup.mfp",function(b){27===b.keyCode&&a.close()});r.on("resize.mfp",
function(){a.updateSize()});a.st.closeOnContentClick||(v+=" mfp-auto-cursor");v&&a.wrap.addClass(v);c=a.wH=r.height();d={};a.fixedContentPos&&a._hasScrollBar(c)&&(f=a._getScrollbarSize())&&(d.marginRight=f);a.fixedContentPos&&(a.isIE7?e("body, html").css("overflow","hidden"):d.overflow="hidden");f=a.st.mainClass;return a.isIE7&&(f+=" mfp-ie7"),f&&a._addClassToMFP(f),a.updateItemHTML(),l("BuildControls"),e("html").css(d),a.bgOverlay.add(a.wrap).prependTo(a.st.prependTo||h),a._lastFocusedEl=document.activeElement,
setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),a._setFocus()):a.bgOverlay.addClass("mfp-ready");g.on("focusin.mfp",a._onFocusIn)},16),a.isOpen=!0,a.updateSize(c),l("Open"),b},close:function(){a.isOpen&&(l("BeforeClose"),a.isOpen=!1,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},a.st.removalDelay)):a._close())},_close:function(){l("Close");var b="mfp-removing mfp-ready ";if(a.bgOverlay.detach(),a.wrap.detach(),
a.container.empty(),a.st.mainClass&&(b+=a.st.mainClass+" "),a._removeClassFromMFP(b),a.fixedContentPos)b={marginRight:""},a.isIE7?e("body, html").css("overflow",""):b.overflow="",e("html").css(b);g.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");!a.st.showCloseBtn||a.st.closeBtnInside&&!0!==a.currTemplate[a.currItem.type]||a.currTemplate.closeBtn&&a.currTemplate.closeBtn.detach();
a._lastFocusedEl&&e(a._lastFocusedEl).focus();a.currItem=null;a.content=null;a.currTemplate=null;a.prevHeight=0;l("AfterClose")},updateSize:function(b){a.isIOS?(b=document.documentElement.clientWidth/window.innerWidth*window.innerHeight,a.wrap.css("height",b),a.wH=b):a.wH=b||r.height();a.fixedContentPos||a.wrap.css("height",a.wH);l("Resize")},updateItemHTML:function(){var b=a.items[a.index];a.contentContainer.detach();a.content&&a.content.detach();b.parsed||(b=a.parseEl(a.index));var c=b.type;if(l("BeforeChange",
[a.currItem?a.currItem.type:"",c]),a.currItem=b,!a.currTemplate[c]){var d=a.st[c]?a.st[c].markup:!1;l("FirstMarkupParse",d);a.currTemplate[c]=d?e(d):!0}u&&u!==b.type&&a.container.removeClass("mfp-"+u+"-holder");d=a["get"+c.charAt(0).toUpperCase()+c.slice(1)](b,a.currTemplate[c]);a.appendContent(d,c);b.preloaded=!0;l("Change",b);u=b.type;a.container.prepend(a.contentContainer);l("AfterChange")},appendContent:function(b,c){(a.content=b)?a.st.showCloseBtn&&a.st.closeBtnInside&&!0===a.currTemplate[c]?
a.content.find(".mfp-close").length||a.content.append(B()):a.content=b:a.content="";l("BeforeAppend");a.container.addClass("mfp-"+c+"-holder");a.contentContainer.append(a.content)},parseEl:function(b){var c,d=a.items[b];if(d.tagName?d={el:e(d)}:(c=d.type,d={data:d,src:d.src}),d.el){for(var f=a.types,p=0;f.length>p;p++)if(d.el.hasClass("mfp-"+f[p])){c=f[p];break}d.src=d.el.attr("data-mfp-src");d.src||(d.src=d.el.attr("href"))}return d.type=c||a.st.type||"inline",d.index=b,d.parsed=!0,a.items[b]=d,
l("ElementParse",d),a.items[b]},addGroup:function(b,c){var d=function(d){d.mfpEl=this;a._openClick(d,b,c)};c||(c={});c.mainEl=b;c.items?(c.isObj=!0,b.off("click.magnificPopup").on("click.magnificPopup",d)):(c.isObj=!1,c.delegate?b.off("click.magnificPopup").on("click.magnificPopup",c.delegate,d):(c.items=b,b.off("click.magnificPopup").on("click.magnificPopup",d)))},_openClick:function(b,c,d){if((void 0!==d.midClick?d.midClick:e.magnificPopup.defaults.midClick)||2!==b.which&&!b.ctrlKey&&!b.metaKey){var f=
void 0!==d.disableOn?d.disableOn:e.magnificPopup.defaults.disableOn;if(f)if(e.isFunction(f)){if(!f.call(a))return!0}else if(f>r.width())return!0;b.type&&(b.preventDefault(),a.isOpen&&b.stopPropagation());d.el=e(b.mfpEl);d.delegate&&(d.items=c.find(d.delegate));a.open(d)}},updateStatus:function(b,c){a.preloader&&(n!==b&&a.container.removeClass("mfp-s-"+n),c||"loading"!==b||(c=a.st.tLoading),c={status:b,text:c},l("UpdateStatus",c),b=c.status,c=c.text,a.preloader.html(c),a.preloader.find("a").on("click",
function(a){a.stopImmediatePropagation()}),a.container.addClass("mfp-s-"+b),n=b)},_checkIfClose:function(b){if(!e(b).hasClass("mfp-prevent-close")){var c=a.st.closeOnContentClick,d=a.st.closeOnBgClick;if(c&&d||!a.content||e(b).hasClass("mfp-close")||a.preloader&&b===a.preloader[0])return!0;if(b===a.content[0]||e.contains(a.content[0],b)){if(c)return!0}else if(d&&e.contains(document,b))return!0;return!1}},_addClassToMFP:function(b){a.bgOverlay.addClass(b);a.wrap.addClass(b)},_removeClassFromMFP:function(b){this.bgOverlay.removeClass(b);
a.wrap.removeClass(b)},_hasScrollBar:function(b){return(a.isIE7?g.height():document.body.scrollHeight)>(b||r.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(b){return b.target===a.wrap[0]||e.contains(a.wrap[0],b.target)?void 0:(a._setFocus(),!1)},_parseMarkup:function(a,c,d){var b;d.data&&(c=e.extend(d.data,c));l("MarkupParse",[a,c,d]);e.each(c,function(c,d){if(void 0===d||!1===d)return!0;if(b=c.split("_"),1<b.length){if(c=a.find(".mfp-"+
b[0]),0<c.length){var e=b[1];"replaceWith"===e?c[0]!==d[0]&&c.replaceWith(d):"img"===e?c.is("img")?c.attr("src",d):c.replaceWith('<img src="'+d+'" class="'+c.attr("class")+'" />'):c.attr(b[1],d)}}else a.find(".mfp-"+c).html(d)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var b=document.createElement("div");b.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";document.body.appendChild(b);a.scrollbarSize=b.offsetWidth-b.clientWidth;document.body.removeChild(b)}return a.scrollbarSize}};
e.magnificPopup={instance:null,proto:x.prototype,modules:[],open:function(a,c){return C(),a=a?e.extend(!0,{},a):{},a.isObj=!0,a.index=c||0,this.instance.open(a)},close:function(){return e.magnificPopup.instance&&e.magnificPopup.instance.close()},registerModule:function(a,c){c.options&&(e.magnificPopup.defaults[a]=c.options);e.extend(this.proto,c.proto);this.modules.push(a)},defaults:{disableOn:0,key:null,midClick:!1,mainClass:"",preloader:!0,focus:"",closeOnContentClick:!1,closeOnBgClick:!0,closeBtnInside:!0,
showCloseBtn:!0,enableEscapeKey:!0,modal:!1,alignTop:!1,removalDelay:0,prependTo:null,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'<button title="%title%" type="button" class="mfp-close">&times;</button>',tClose:"Close (Esc)",tLoading:"Loading..."}};e.fn.magnificPopup=function(b){C();var c=e(this);if("string"==typeof b)if("open"===b){var d,f=A?c.data("magnificPopup"):c[0].magnificPopup,p=parseInt(arguments[1],10)||0;f.items?d=f.items[p]:(d=c,f.delegate&&(d=d.find(f.delegate)),
d=d.eq(p));a._openClick({mfpEl:d},c,f)}else a.isOpen&&a[b].apply(a,Array.prototype.slice.call(arguments,1));else b=e.extend(!0,{},b),A?c.data("magnificPopup",b):c[0].magnificPopup=b,a.addGroup(c,b);return c};var w,y,z,H=function(){z&&(y.after(z.addClass(w)).detach(),z=null)};e.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",markup:"",tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");k("Close.inline",function(){H()})},getInline:function(b,c){if(H(),
b.src){c=a.st.inline;var d=e(b.src);if(d.length){var f=d[0].parentNode;f&&f.tagName&&(y||(w=c.hiddenClass,y=m(w),w="mfp-"+w),z=d.after(y).detach().removeClass(w));a.updateStatus("ready")}else a.updateStatus("error",c.tNotFound),d=e("<div>");return b.inlineElement=d,d}return a.updateStatus("ready"),a._parseMarkup(c,{},b),c}}});var q,I=function(){q&&h.removeClass(q);a.req&&a.req.abort()};e.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'<a href="%url%">The content</a> could not be loaded.'},
proto:{initAjax:function(){a.types.push("ajax");q=a.st.ajax.cursor;k("Close.ajax",I);k("BeforeChange.ajax",I)},getAjax:function(b){q&&h.addClass(q);a.updateStatus("loading");var c=e.extend({url:b.src,success:function(c,f,p){c={data:c,xhr:p};l("ParseAjax",c);a.appendContent(e(c.data),"ajax");b.finished=!0;q&&h.removeClass(q);a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");l("AjaxContentAdded")},error:function(){q&&h.removeClass(q);b.finished=b.loadError=
!0;a.updateStatus("error",a.st.ajax.tError.replace("%url%",b.src))}},a.st.ajax.settings);return a.req=e.ajax(c),""}}});var t,L=function(b){if(b.data&&void 0!==b.data.title)return b.data.title;var c=a.st.image.titleSrc;if(c){if(e.isFunction(c))return c.call(a,b);if(b.el)return b.el.attr(c)||""}return""};e.magnificPopup.registerModule("image",{options:{markup:'<div class="mfp-figure"><div class="mfp-close"></div><figure><div class="mfp-img"></div><figcaption><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></figcaption></figure></div>',
cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:!0,tError:'<a href="%url%">The image</a> could not be loaded.'},proto:{initImage:function(){var b=a.st.image;a.types.push("image");k("Open.image",function(){"image"===a.currItem.type&&b.cursor&&h.addClass(b.cursor)});k("Close.image",function(){b.cursor&&h.removeClass(b.cursor);r.off("resize.mfp")});k("Resize.image",a.resizeImage);a.isLowIE&&k("AfterChange",a.resizeImage)},resizeImage:function(){var b=a.currItem;if(b&&b.img&&a.st.image.verticalFit){var c=
0;a.isLowIE&&(c=parseInt(b.img.css("padding-top"),10)+parseInt(b.img.css("padding-bottom"),10));b.img.css("max-height",a.wH-c)}},_onImageHasSize:function(b){b.img&&(b.hasSize=!0,t&&clearInterval(t),b.isCheckingImgSize=!1,l("ImageHasSize",b),b.imgHidden&&(a.content&&a.content.removeClass("mfp-loading"),b.imgHidden=!1))},findImageSize:function(b){var c=0,d=b.img[0],e=function(f){t&&clearInterval(t);t=setInterval(function(){return 0<d.naturalWidth?(a._onImageHasSize(b),void 0):(200<c&&clearInterval(t),
c++,3===c?e(10):40===c?e(50):100===c&&e(500),void 0)},f)};e(1)},getImage:function(b,c){var d=0,f=function(){b&&(b.img[0].complete?(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("ready")),b.hasSize=!0,b.loaded=!0,l("ImageLoadComplete")):(d++,200>d?setTimeout(f,100):p()))},p=function(){b&&(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("error",k.tError.replace("%url%",b.src))),b.hasSize=!0,b.loaded=!0,b.loadError=!0)},k=a.st.image,h=c.find(".mfp-img");
if(h.length){var g=document.createElement("img");g.className="mfp-img";b.img=e(g).on("load.mfploader",f).on("error.mfploader",p);g.src=b.src;h.is("img")&&(b.img=b.img.clone());g=b.img[0];0<g.naturalWidth?b.hasSize=!0:g.width||(b.hasSize=!1)}return a._parseMarkup(c,{title:L(b),img_replaceWith:b.img},b),a.resizeImage(),b.hasSize?(t&&clearInterval(t),b.loadError?(c.addClass("mfp-loading"),a.updateStatus("error",k.tError.replace("%url%",b.src))):(c.removeClass("mfp-loading"),a.updateStatus("ready")),
c):(a.updateStatus("loading"),b.loading=!0,b.hasSize||(b.imgHidden=!0,c.addClass("mfp-loading"),a.findImageSize(b)),c)}}});var D;e.magnificPopup.registerModule("zoom",{options:{enabled:!1,easing:"ease-in-out",duration:300,opener:function(a){return a.is("img")?a:a.find("img")}},proto:{initZoom:function(){var b,c=a.st.zoom;if(c.enabled&&a.supportsTransition){var d,e,p=c.duration,g=function(a){a=a.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var b={position:"fixed",
zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};return b["-webkit-transition"]=b["-moz-transition"]=b["-o-transition"]=b.transition="all "+c.duration/1E3+"s "+c.easing,a.css(b),a},h=function(){a.content.css("visibility","visible")};k("BuildControls.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.content.css("visibility","hidden"),b=a._getItemToZoom(),!b)return h(),void 0;e=g(b);e.css(a._getOffset());a.wrap.append(e);d=setTimeout(function(){e.css(a._getOffset(!0));d=setTimeout(function(){h();
setTimeout(function(){e.remove();b=e=null;l("ZoomAnimationEnded")},16)},p)},16)}});k("BeforeClose.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.st.removalDelay=p,!b){if(b=a._getItemToZoom(),!b)return;e=g(b)}e.css(a._getOffset(!0));a.wrap.append(e);a.content.css("visibility","hidden");setTimeout(function(){e.css(a._getOffset())},16)}});k("Close.zoom",function(){a._allowZoom()&&(h(),e&&e.remove(),b=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return a.currItem.hasSize?
a.currItem.img:!1},_getOffset:function(b){var c=b?a.currItem.img:a.st.zoom.opener(a.currItem.el||a.currItem);b=c.offset();var d=parseInt(c.css("padding-top"),10),f=parseInt(c.css("padding-bottom"),10);b.top-=e(window).scrollTop()-d;c={width:c.width(),height:(A?c.innerHeight():c[0].offsetHeight)-f-d};return(void 0===D&&(D=void 0!==document.createElement("p").style.MozTransform),D)?c["-moz-transform"]=c.transform="translate("+b.left+"px,"+b.top+"px)":(c.left=b.left,c.top=b.top),c}}});var E=function(b){if(a.currTemplate.iframe){var c=
a.currTemplate.iframe.find("iframe");c.length&&(b||(c[0].src="//about:blank"),a.isIE8&&c.css("display",b?"block":"none"))}};e.magnificPopup.registerModule("iframe",{options:{markup:'<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allowfullscreen></iframe></div>',srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v=",src:"//www.youtube.com/embed/%id%?autoplay=1"},vimeo:{index:"vimeo.com/",id:"/",src:"//player.vimeo.com/video/%id%?autoplay=1"},
gmaps:{index:"//maps.google.",src:"%id%&output=embed"}}},proto:{initIframe:function(){a.types.push("iframe");k("BeforeChange",function(a,c,d){c!==d&&("iframe"===c?E():"iframe"===d&&E(!0))});k("Close.iframe",function(){E()})},getIframe:function(b,c){var d=b.src,f=a.st.iframe;e.each(f.patterns,function(){return-1<d.indexOf(this.index)?(this.id&&(d="string"==typeof this.id?d.substr(d.lastIndexOf(this.id)+this.id.length,d.length):this.id.call(this,d)),d=this.src.replace("%id%",d),!1):void 0});var g={};
return f.srcAction&&(g[f.srcAction]=d),a._parseMarkup(c,g,b),a.updateStatus("ready"),c}}});var F=function(b){var c=a.items.length;return b>c-1?b-c:0>b?c+b:b},J=function(a,c,d){return a.replace(/%curr%/gi,c+1).replace(/%total%/gi,d)};e.magnificPopup.registerModule("gallery",{options:{enabled:!1,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',preload:[0,2],navigateByImgClick:!0,arrows:!0,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",
tCounter:"%curr% of %total%"},proto:{initGallery:function(){var b=a.st.gallery,c=!!e.fn.mfpFastClick;return a.direction=!0,b&&b.enabled?(v+=" mfp-gallery",k("Open.mfp-gallery",function(){b.navigateByImgClick&&a.wrap.on("click.mfp-gallery",".mfp-img",function(){return 1<a.items.length?(a.next(),!1):void 0});g.on("keydown.mfp-gallery",function(b){37===b.keyCode?a.prev():39===b.keyCode&&a.next()})}),k("UpdateStatus.mfp-gallery",function(b,c){c.text&&(c.text=J(c.text,a.currItem.index,a.items.length))}),
k("MarkupParse.mfp-gallery",function(c,e,g,h){c=a.items.length;g.counter=1<c?J(b.tCounter,h.index,c):""}),k("BuildControls.mfp-gallery",function(){if(1<a.items.length&&b.arrows&&!a.arrowLeft){var d=b.arrowMarkup,f=a.arrowLeft=e(d.replace(/%title%/gi,b.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close"),d=a.arrowRight=e(d.replace(/%title%/gi,b.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close"),g=c?"mfpFastClick":"click";f[g](function(){a.prev()});d[g](function(){a.next()});
a.isIE7&&(m("b",f[0],!1,!0),m("a",f[0],!1,!0),m("b",d[0],!1,!0),m("a",d[0],!1,!0));a.container.append(f.add(d))}}),k("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();a._preloadTimeout=null},16)}),k("Close.mfp-gallery",function(){g.off(".mfp-gallery");a.wrap.off("click.mfp-gallery");a.arrowLeft&&c&&a.arrowLeft.add(a.arrowRight).destroyMfpFastClick();a.arrowRight=a.arrowLeft=null}),void 0):!1},next:function(){a.direction=
!0;a.index=F(a.index+1);a.updateItemHTML()},prev:function(){a.direction=!1;a.index=F(a.index-1);a.updateItemHTML()},goTo:function(b){a.direction=b>=a.index;a.index=b;a.updateItemHTML()},preloadNearbyImages:function(){var b=a.st.gallery.preload;var c=Math.min(b[0],a.items.length),d=Math.min(b[1],a.items.length);for(b=1;(a.direction?d:c)>=b;b++)a._preloadItem(a.index+b);for(b=1;(a.direction?c:d)>=b;b++)a._preloadItem(a.index-b)},_preloadItem:function(b){if(b=F(b),!a.items[b].preloaded){var c=a.items[b];
c.parsed||(c=a.parseEl(b));l("LazyLoad",c);"image"===c.type&&(c.img=e('<img class="mfp-img" />').on("load.mfploader",function(){c.hasSize=!0}).on("error.mfploader",function(){c.hasSize=!0;c.loadError=!0;l("LazyLoadError",c)}).attr("src",c.src));c.preloaded=!0}}}});e.magnificPopup.registerModule("retina",{options:{replaceSrc:function(a){return a.src.replace(/\.\w+$/,function(a){return"@2x"+a})},ratio:1},proto:{initRetina:function(){if(1<window.devicePixelRatio){var b=a.st.retina,c=b.ratio,c=isNaN(c)?
c():c;1<c&&(k("ImageHasSize.retina",function(a,b){b.img.css({"max-width":b.img[0].naturalWidth/c,width:"100%"})}),k("ElementParse.retina",function(a,e){e.src=b.replaceSrc(e,c)}))}}}});(function(){var a="ontouchstart"in window,c=function(){r.off("touchmove"+d+" touchend"+d)},d=".mfpFastClick";e.fn.mfpFastClick=function(b){return e(this).each(function(){var f,g=e(this);if(a){var h,k,l,n,m,q;g.on("touchstart"+d,function(a){n=!1;q=1;m=a.originalEvent?a.originalEvent.touches[0]:a.touches[0];k=m.clientX;
l=m.clientY;r.on("touchmove"+d,function(a){m=a.originalEvent?a.originalEvent.touches:a.touches;q=m.length;m=m[0];(10<Math.abs(m.clientX-k)||10<Math.abs(m.clientY-l))&&(n=!0,c())}).on("touchend"+d,function(a){c();n||1<q||(f=!0,a.preventDefault(),clearTimeout(h),h=setTimeout(function(){f=!1},1E3),b())})})}g.on("click"+d,function(){f||b()})})};e.fn.destroyMfpFastClick=function(){e(this).off("touchstart"+d+" click"+d);a&&r.off("touchmove"+d+" touchend"+d)}})();C()})(window.jQuery||window.Zepto);
