var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");
(function(){var a=function(){if(-1==navigator.platform.indexOf("iPhone")&&-1==navigator.platform.indexOf("iPod")||-1==navigator.platform.indexOf("iPad"))$(".js-full-height").css("height",$(window).height()),$(window).resize(function(){$(".js-full-height").css("height",$(window).height())})},c=function(){$("body").on("click",".scroll-btn",function(a){a.preventDefault();$("html, body").animate({scrollTop:$($(this).closest('[data-next="yes"]').next()).offset().top},1E3,"easeInOutExpo");return!1})},b=
function(){$(".fh5co-counter-style-1").waypoint(function(a){var b=$(this.element).attr("class");"down"!==a||$(this.element).hasClass("animated")||(setTimeout(function(){$("."+b).find(".js-counter").countTo({formatter:function(a,b){return a.toFixed(b.decimals)}})},200),$(this.element).addClass("animated"))},{offset:"75%"});$(".fh5co-counter-style-2").waypoint(function(a){var b=$(this.element).attr("class");"down"!==a||$(this.element).hasClass("animated")||(setTimeout(function(){$("."+b).find(".js-counter").countTo({formatter:function(a,
b){return a.toFixed(b.decimals)}})},200),$(this.element).addClass("animated"))},{offset:"75%"})},d=function(){$(document).click(function(a){var b=$("#fh5co-offcanvass, .js-fh5co-mobile-toggle");b.is(a.target)||0!==b.has(a.target).length||($("html").removeClass("mobile-menu-expanded"),$(".js-fh5co-mobile-toggle").removeClass("active"))})},e=function(){$("body").on("click",".js-fh5co-nav-toggle",function(a){$("#navbar").is(":visible")?$(this).removeClass("active"):$(this).addClass("active");a.preventDefault()})},
f=function(){0==$("#fh5co-offcanvass").length&&(0<$(".fh5co-nav-style-1").length&&($("body").prepend('<div id="fh5co-offcanvass" />'),$(".fh5co-link-wrap").each(function(){$("#fh5co-offcanvass").append($(this).find('[data-offcanvass="yes"]').clone())}),$("#fh5co-offcanvass").find(".js-fh5co-mobile-toggle").remove(),$("#fh5co-offcanvass, #fh5co-page").addClass($(".fh5co-nav-style-1").data("offcanvass-position")),$("#fh5co-offcanvass").addClass("offcanvass-nav-style-1")),0<$(".fh5co-nav-style-2").length&&
($("body").prepend('<div id="fh5co-offcanvass" />'),$(".fh5co-link-wrap").each(function(){$("#fh5co-offcanvass").append($(this).find('[data-offcanvass="yes"]').clone())}),$("#fh5co-offcanvass").find(".js-fh5co-mobile-toggle").remove(),$("#fh5co-offcanvass, #fh5co-page").addClass($(".fh5co-nav-style-2").data("offcanvass-position")),$("#fh5co-offcanvass").addClass("offcanvass-nav-style-2")));$("body").on("click",".js-fh5co-mobile-toggle",function(a){$(this).toggleClass("active");$("html").toggleClass("mobile-menu-expanded")});
769>$(window).width()&&$("body, html").addClass("fh5co-overflow");$(window).resize(function(){769>$(window).width()&&$("body, html").addClass("fh5co-overflow");767<$(window).width()&&$("html").hasClass("mobile-menu-expanded")&&($(".js-fh5co-mobile-toggle").removeClass("active"),$("html").removeClass("mobile-menu-expanded"))})};$(function(){a();c();$(window).stellar();b();d();e();$(".image-popup").magnificPopup({type:"image",removalDelay:10,titleSrc:"title",gallery:{enabled:!1}});f()})})();
