window.Modernizr=function(f,e,z){function r(b,a){return typeof b===a}function B(b,a){for(var c in b){var l=b[c];if(!~(""+l).indexOf("-")&&p[l]!==z)return"pfx"==a?l:!0}return!1}function q(b,a,c){var l=b.charAt(0).toUpperCase()+b.slice(1),d=(b+" "+C.join(l+" ")+l).split(" ");if(r(a,"string")||r(a,"undefined"))a=B(d,a);else a:{d=(b+" "+D.join(l+" ")+l).split(" "),b=d;for(var e in b)if(l=a[b[e]],l!==z){a=!1===c?b[e]:r(l,"function")?l.bind(c||a):l;break a}a=!1}return a}function P(){g.input=function(b){for(var a=
0,c=b.length;a<c;a++)E[b[a]]=b[a]in n;return E.list&&(E.list=!!e.createElement("datalist")&&!!f.HTMLDataListElement),E}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));g.inputtypes=function(b){for(var a=0,c,d,G,g=b.length;a<g;a++)n.setAttribute("type",d=b[a]),(c="text"!==n.type)&&(n.value=w,n.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(d)&&n.style.WebkitAppearance!==z?(u.appendChild(n),G=e.defaultView,c=G.getComputedStyle&&"textfield"!==
G.getComputedStyle(n,null).WebkitAppearance&&0!==n.offsetHeight,u.removeChild(n)):/^(search|tel)$/.test(d)||(/^(url|email)$/.test(d)?c=n.checkValidity&&!1===n.checkValidity():c=n.value!=w)),O[b[a]]=!!c;return O}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var g={},u=e.documentElement,d=e.createElement("modernizr"),p=d.style,n=e.createElement("input"),w=":)",x={}.toString,A=" -webkit- -moz- -o- -ms- ".split(" "),C=["Webkit","Moz","O","ms"],D=["webkit",
"moz","o","ms"],d={},O={},E={},H=[],I=H.slice,J,y=function(b,a,c,d){var l,g,f,k=e.createElement("div"),v=e.body,m=v||e.createElement("body");if(parseInt(c,10))for(;c--;){var K=e.createElement("div");K.id=d?d[c]:"modernizr"+(c+1);k.appendChild(K)}return l=['&#173;<style id="smodernizr">',b,"</style>"].join(""),k.id="modernizr",(v?k:m).innerHTML+=l,m.appendChild(k),v||(m.style.background="",m.style.overflow="hidden",f=u.style.overflow,u.style.overflow="hidden",u.appendChild(m)),g=a(k,b),v?k.parentNode.removeChild(k):
(m.parentNode.removeChild(m),u.style.overflow=f),!!g},L=function(){var b={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(a,c){c=c||e.createElement(b[a]||"div");a="on"+a;var d=a in c;return d||(c.setAttribute||(c=e.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(a,""),d=r(c[a],"function"),r(c[a],"undefined")||(c[a]=z),c.removeAttribute(a))),d}}(),t={}.hasOwnProperty,F;r(t,"undefined")||r(t.call,"undefined")?F=function(b,
a){return a in b&&r(b.constructor.prototype[a],"undefined")}:F=function(b,a){return t.call(b,a)};Function.prototype.bind||(Function.prototype.bind=function(b){var a=this;if("function"!=typeof a)throw new TypeError;var c=I.call(arguments,1),d=function(){if(this instanceof d){var e=function(){};e.prototype=a.prototype;var e=new e,l=a.apply(e,c.concat(I.call(arguments)));return Object(l)===l?l:e}return a.apply(b,c.concat(I.call(arguments)))};return d});d.flexbox=function(){return q("flexWrap")};d.canvas=
function(){var b=e.createElement("canvas");return!!b.getContext&&!!b.getContext("2d")};d.canvastext=function(){return!!g.canvas&&!!r(e.createElement("canvas").getContext("2d").fillText,"function")};d.webgl=function(){return!!f.WebGLRenderingContext};d.touch=function(){var b;return"ontouchstart"in f||f.DocumentTouch&&e instanceof DocumentTouch?b=!0:y(["@media (",A.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(a){b=9===a.offsetTop}),b};d.geolocation=
function(){return"geolocation"in navigator};d.postmessage=function(){return!!f.postMessage};d.websqldatabase=function(){return!!f.openDatabase};d.indexedDB=function(){return!!q("indexedDB",f)};d.hashchange=function(){return L("hashchange",f)&&(e.documentMode===z||7<e.documentMode)};d.history=function(){return!!f.history&&!!history.pushState};d.draganddrop=function(){var b=e.createElement("div");return"draggable"in b||"ondragstart"in b&&"ondrop"in b};d.websockets=function(){return"WebSocket"in f||
"MozWebSocket"in f};d.rgba=function(){p.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+p.backgroundColor).indexOf("rgba")};d.hsla=function(){p.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+p.backgroundColor).indexOf("rgba")||!!~(""+p.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){p.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(p.background)};d.backgroundsize=function(){return q("backgroundSize")};d.borderimage=
function(){return q("borderImage")};d.borderradius=function(){return q("borderRadius")};d.boxshadow=function(){return q("boxShadow")};d.textshadow=function(){return""===e.createElement("div").style.textShadow};d.opacity=function(){p.cssText=A.join("opacity:.55;")+"";return/^0.55$/.test(p.opacity)};d.cssanimations=function(){return q("animationName")};d.csscolumns=function(){return q("columnCount")};d.cssgradients=function(){p.cssText=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
A.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);return!!~(""+p.backgroundImage).indexOf("gradient")};d.cssreflections=function(){return q("boxReflect")};d.csstransforms=function(){return!!q("transform")};d.csstransforms3d=function(){var b=!!q("perspective");return b&&"webkitPerspective"in u.style&&y("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(a,c){b=9===a.offsetLeft&&3===a.offsetHeight}),b};d.csstransitions=
function(){return q("transition")};d.fontface=function(){var b;return y('@font-face {font-family:"font";src:url("https://")}',function(a,c){a=e.getElementById("smodernizr");a=(a=a.sheet||a.styleSheet)?a.cssRules&&a.cssRules[0]?a.cssRules[0].cssText:a.cssText||"":"";b=/src/i.test(a)&&0===a.indexOf(c.split(" ")[0])}),b};d.generatedcontent=function(){var b;return y(['#modernizr{font:0/0 a}#modernizr:after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(a){b=3<=a.offsetHeight}),b};
d.video=function(){var b=e.createElement("video"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),a.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),a.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return a};d.audio=function(){var b=e.createElement("audio"),a=!1;try{if(a=!!b.canPlayType)a=new Boolean(a),a.ogg=b.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),
a.mp3=b.canPlayType("audio/mpeg;").replace(/^no$/,""),a.wav=b.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),a.m4a=(b.canPlayType("audio/x-m4a;")||b.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return a};d.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(b){return!1}};d.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(b){return!1}};
d.webworkers=function(){return!!f.Worker};d.applicationcache=function(){return!!f.applicationCache};d.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};d.inlinesvg=function(){var b=e.createElement("div");return b.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(b.firstChild&&b.firstChild.namespaceURI)};d.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(x.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};d.svgclippaths=
function(){return!!e.createElementNS&&/SVGClipPath/.test(x.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var M in d)F(d,M)&&(J=M.toLowerCase(),g[J]=d[M](),H.push((g[J]?"":"no-")+J));g.input||P();g.addTest=function(b,a){if("object"==typeof b)for(var c in b)F(b,c)&&g.addTest(c,b[c]);else{b=b.toLowerCase();if(g[b]!==z)return g;a="function"==typeof a?a():a;u.className+=" "+(a?"":"no-")+b;g[b]=a}return g};p.cssText="";return d=n=null,function(b,a){function c(){var a=p.elements;
return"string"==typeof a?a.split(" "):a}function d(a){var b=h[a[n]];return b||(b={},q++,a[n]=q,h[q]=b),b}function e(b,c,e){c||(c=a);if(N)return c.createElement(b);e||(e=d(c));var h;return e.cache[b]?h=e.cache[b].cloneNode():m.test(b)?h=(e.cache[b]=e.createElem(b)).cloneNode():h=e.createElem(b),h.canHaveChildren&&!v.test(b)?e.frag.appendChild(h):h}function g(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag());a.createElement=function(c){return p.shivMethods?
e(c,a,b):b.createElem(c)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/\w+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'})+");return n}")(p,b.frag)}function f(b){b||(b=a);var c=d(b);if(p.shivCSS&&!K&&!c.hasCSS){var e=b;var h=e.createElement("p");e=e.getElementsByTagName("head")[0]||e.documentElement;h=(h.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",
e.insertBefore(h.lastChild,e.firstChild));c.hasCSS=!!h}return N||g(b,c),b}var k=b.html5||{},v=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,m=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,K,n="_html5shiv",q=0,h={},N;(function(){try{var b=a.createElement("a");b.innerHTML="<xyz></xyz>";K="hidden"in b;var c;if(!(c=1==b.childNodes.length)){a.createElement("a");var d=a.createDocumentFragment();c="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}N=c}catch(Q){N=K=!0}})();var p={elements:k.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==k.shivCSS,supportsUnknownElements:N,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:f,createElement:e,createDocumentFragment:function(b,e){b||(b=a);if(N)return b.createDocumentFragment();
e=e||d(b);b=e.frag.cloneNode();e=0;for(var h=c(),m=h.length;e<m;e++)b.createElement(h[e]);return b}};b.html5=p;f(a)}(this,e),g._version="2.6.2",g._prefixes=A,g._domPrefixes=D,g._cssomPrefixes=C,g.mq=function(b){var a=f.matchMedia||f.msMatchMedia;if(a)return a(b).matches;var c;return y("@media "+b+" { #modernizr { position: absolute; } }",function(a){c="absolute"==(f.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position}),c},g.hasEvent=L,g.testProp=function(b){return B([b])},g.testAllProps=
q,g.testStyles=y,g.prefixed=function(b,a,c){return a?q(b,a,c):q(b,"pfx")},u.className=u.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+H.join(" ")),g}(this,this.document);
(function(f,e,z){function r(a){return"[object Function]"==A.call(a)}function B(a){return"string"==typeof a}function q(){}function P(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function g(){var a=C.shift();D=1;a?a.t?w(function(){("c"==a.t?b.injectCss:b.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),g()):D=0}function u(a,c,d,f,n,q,k){function v(b){if(!l&&P(m.readyState)&&(G.r=l=1,!D&&g(),m.onload=m.onreadystatechange=null,b)){"img"!=a&&w(function(){H.removeChild(m)},50);for(var e in t[c])t[c].hasOwnProperty(e)&&
t[c][e].onload()}}k=k||b.errorTimeout;var m=e.createElement(a),l=0,p=0,G={t:d,s:c,e:n,a:q,x:k};1===t[c]&&(p=1,t[c]=[]);"object"==a?m.data=c:(m.src=c,m.type=a);m.width=m.height="0";m.onerror=m.onload=m.onreadystatechange=function(){v.call(this,p)};C.splice(f,0,G);"img"!=a&&(p||2===t[c]?(H.insertBefore(m,E?null:x),w(v,k)):t[c].push(m))}function d(a,b,e,d,f){return D=0,b=b||"j",B(a)?u("c"==b?J:I,a,b,this.i++,e,d,f):(C.splice(this.i++,0,a),1==C.length&&g()),this}function p(){var a=b;return a.loader={load:d,
i:0},a}var n=e.documentElement,w=f.setTimeout,x=e.getElementsByTagName("script")[0],A={}.toString,C=[],D=0,O="MozAppearance"in n.style,E=O&&!!e.createRange().compareNode,H=E?n:x.parentNode,n=f.opera&&"[object Opera]"==A.call(f.opera),n=!!e.attachEvent&&!n,I=O?"object":n?"script":"img",J=n?"script":I,y=Array.isArray||function(a){return"[object Array]"==A.call(a)},L=[],t={},F={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},M;var b=function(a){function c(a){a=a.split("!");var b=L.length,
c=a.pop(),e=a.length,c={url:c,origUrl:c,prefixes:a},d,h;for(h=0;h<e;h++){var g=a[h].split("=");(d=F[g.shift()])&&(c=d(c,g))}for(h=0;h<b;h++)c=L[h](c);return c}function e(a,b,e,d,g){var h=c(a),f=h.autoCallback;h.url.split(".").pop().split("?").shift();h.bypass||(b&&(b=r(b)?b:b[a]||b[d]||b[a.split("/").pop().split("?")[0]]),h.instead?h.instead(a,b,e,d,g):(t[h.url]?h.noexec=!0:t[h.url]=1,e.load(h.url,h.forceCSS||!h.forceJS&&"css"==h.url.split(".").pop().split("?").shift()?"c":z,h.noexec,h.attrs,h.timeout),
(r(b)||r(f))&&e.load(function(){p();b&&b(h.origUrl,g,d);f&&f(h.origUrl,g,d);t[h.url]=2})))}function d(a,b){function c(a,c){if(a)if(B(a))c||(h=function(){var a=[].slice.call(arguments);f.apply(this,a);k()}),e(a,h,b,0,d);else{if(Object(a)===a)for(l in m=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(l)&&(!c&&!--m&&(r(h)?h=function(){var a=[].slice.call(arguments);f.apply(this,a);k()}:h[l]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);k()}}(f[l])),e(a[l],h,b,l,d))}else!c&&k()}var d=!!a.test,g=a.load||a.both,h=a.callback||q,f=h,k=a.complete||q,m,l;c(d?a.yep:a.nope,!!g);g&&c(g)}var g,f=this.yepnope.loader;if(B(a))e(a,0,f,0);else if(y(a))for(g=0;g<a.length;g++){var k=a[g];B(k)?e(k,0,f,0):y(k)?b(k):Object(k)===k&&d(k,f)}else Object(a)===a&&d(a,f)};b.addPrefix=function(a,b){F[a]=b};b.addFilter=function(a){L.push(a)};b.errorTimeout=1E4;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
M=function(){e.removeEventListener("DOMContentLoaded",M,0);e.readyState="complete"},0));f.yepnope=p();f.yepnope.executeStack=g;f.yepnope.injectJs=function(a,c,d,f,n,p){var k=e.createElement("script"),l,m;f=f||b.errorTimeout;k.src=a;for(m in d)k.setAttribute(m,d[m]);c=p?g:c||q;k.onreadystatechange=k.onload=function(){!l&&P(k.readyState)&&(l=1,c(),k.onload=k.onreadystatechange=null)};w(function(){l||(l=1,c(1))},f);n?k.onload():x.parentNode.insertBefore(k,x)};f.yepnope.injectCss=function(a,b,d,f,n,p){f=
e.createElement("link");var c;b=p?g:b||q;f.href=a;f.rel="stylesheet";f.type="text/css";for(c in d)f.setAttribute(c,d[c]);n||(x.parentNode.insertBefore(f,x),w(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
