var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,a,c){b instanceof String&&(b=String(b));for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a.call(c,f,e,b))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var a=0;return $jscomp.iteratorPrototype(function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,a){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var c=0,d={next:function(){if(c<b.length){var e=c++;return{value:a(e,b[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.values",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a,b){return b})}},"es6","es3");
$(document).ready(function(){$("#toolbox-tools").draggable({handle:".panel-heading"}).resizable({handles:"e, w, s, se"});$("#dynamic_map").click(function(){updateDynamicMapFilter(this.checked)});$("#map_interactive").click(function(){updateInteractiveMapFilter(this.checked)});$("#time_step_scale").click(function(){mustScale=this.checked;updateSceneFilters();updateMapLayerDisplay(mustScale)});$("#map_type").change(function(){updateMapLayerType($(this).find(":selected").val())});$("#time_step_int").slider({range:!0,
min:TIME_STEP_LOWER_BOUND,max:TIME_STEP_UPPER_BOUND,values:[TIME_STEP_LOWER_BOUND,TIME_STEP_UPPER_BOUND],slide:function(b,a){timeStepLowerBound=a.values[0];timeStepUpperBound=a.values[1];updateSceneFilters();$("#time_step_int_value").text(getTimeStampFromStep(a.values[0]).toLocaleString()+" - "+getTimeStampFromStep(a.values[1]).toLocaleString());newSizeY=Math.abs(a.values[1]-a.values[0]);offsetNY=a.values[0];$("#one_layer_extrusion").prop("checked",!1);mustExtrude=!1;extrudeLayer=-1;updateMapLayerDisplay(mustScale);
updateSceneFilters()}});$("#cell_y_int").slider({range:!0,min:X_LOWER_BOUND,max:X_UPPER_BOUND,values:[X_LOWER_BOUND,X_UPPER_BOUND],slide:function(b,a){yLowerBound=a.values[0];yUpperBound=a.values[1];$("#cell_y_int_value").text(getLatitudeFromY(a.values[0],!1).toFixed(4)+" - "+getLatitudeFromY(a.values[1]).toFixed(4));newSizeX=Math.abs(a.values[1]-a.values[0]);offsetNZ=a.values[0];updateMapLayerDisplay(mustScale);updateSceneFilters()}});$("#cell_x_int").slider({range:!0,min:X_LOWER_BOUND,max:X_UPPER_BOUND,
values:[X_LOWER_BOUND,X_UPPER_BOUND],slide:function(b,a){xLowerBound=a.values[0];xUpperBound=a.values[1];$("#cell_x_int_value").text(getLongitudeFromX(a.values[0],yLowerBound,!1).toFixed(4)+" - "+getLongitudeFromX(a.values[1],yUpperBound,!1).toFixed(4));newSizeZ=Math.abs(a.values[1]-a.values[0]);offsetNX=a.values[0];updateMapLayerDisplay(mustScale);updateSceneFilters()}});$("#zscore_int").slider({range:!0,min:1E3*ZSCORE_LOWER_BOUND,max:1E3*ZSCORE_UPPER_BOUND,values:[1E3*ZSCORE_LOWER_BOUND,1E3*ZSCORE_UPPER_BOUND],
slide:function(b,a){zScoreLowerBound=a.values[0]/1E3;zScoreUpperBound=a.values[1]/1E3;$("#zscore_int_value").text(zScoreLowerBound+" - "+zScoreUpperBound);updateSceneFilters()}});$("#brush_size").slider({min:1,max:5,create:function(){$("#brush_size_handle").text($(this).slider("value"))},slide:function(b,a){BRUSH_SIZE=a.value;$("#brush_size_handle").text(BRUSH_SIZE);updateBrushSizeFilter()}});$("#one_layer_extrusion").click(function(){mustExtrude=this.checked;updateOneLayerFilter();updateBrushSizeFilter()});
$("#one_layer").slider({min:TIME_STEP_LOWER_BOUND,max:TIME_STEP_UPPER_BOUND,create:function(){$("#one_layer_handle").text($(this).slider("value"))},slide:function(b,a){$("#one_layer_handle").text(a.value);offsetNY=extrudeLayer=a.value;updateOneLayerFilter()}});$("#map_opacity").slider({min:1,max:10,create:function(){$("#map_opacity_handle").text($(this).slider("value"))},slide:function(b,a){$("#map_opacity_handle").text(a.value/10);updateMapAlphaFilter(a.value/10)}});$("#map_offset_x").slider({min:-200,
max:sizeLng,create:function(){$("#map_offset_x_handle").text($(this).slider("value"))},slide:function(b,a){$("#map_offset_x_handle").text(a.value);updateMapOffsetX(a.value)}});$("#map_offset_y").slider({min:-200,max:sizeTime,create:function(){$("#map_offset_y_handle").text($(this).slider("value"))},slide:function(b,a){$("#map_offset_y_handle").text(a.value);updateMapOffsetY(a.value)}});$("#map_offset_z").slider({min:-200,max:sizeLat,create:function(){$("#map_offset_z_handle").text($(this).slider("value"))},
slide:function(b,a){$("#map_offset_z_handle").text(a.value);updateMapOffsetZ(a.value)}});$("#map_display").slider({min:0,max:10,create:function(){$("#map_display_handle").text($(this).slider("value"))},slide:function(b,a){$("#map_display_handle").text(a.value/10);updateMapAlphaFilter(a.value/10)}});$("#camera_fov").slider({min:50,max:100,value:90,create:function(){$("#camera_fov_handle").text($(this).slider("value"))},slide:function(b,a){$("#camera_fov_handle").text(a.value);updateCameraFOVFilter(a.value)}});
$("#zoom_speed").slider({min:1,max:10,create:function(){$("#zoom_speed_handle").text($(this).slider("value"))},slide:function(b,a){$("#zoom_speed_handle").text(a.value);updateZoomSpeedFilter(a.value)}});$("#map_scale_x").slider({min:1,max:1E3,create:function(){$("#map_scale_x_handle").text($(this).slider("value"))},slide:function(b,a){$("#map_scale_x_handle").text(a.value/100);updateMapScaleXFilter(a.value/100)}});$("#map_scale_y").slider({min:1,max:1E3,create:function(){$("#map_scale_y_handle").text($(this).slider("value"))},
slide:function(b,a){$("#map_scale_y_handle").text(a.value/100);updateMapScaleYFilter(a.value/100)}});$("#toggle-toolbox-tools").on("click",function(){var b=$("#toolbox-tools");void 0==$(b).data("org-height")?($(b).data("org-height",$(b).css("height")),$(b).css("height","41px")):($(b).css("height",$(b).data("org-height")),$(b).removeData("org-height"));$(this).toggleClass("fa-chevron-down").toggleClass("fa-chevron-right")});$("#sortable").sortable({stop:function(b,a){var c=[];$.each($(".draggable-group"),
function(b,a){c.push($(a).attr("id"))})}});$("#sortable").disableSelection();$.each($(".draggable-group"),function(b,a){b=$(a).find(".toggle-button-group");$(b).on("click",function(){$(a).toggleClass("minimized");$(this).toggleClass("fa-caret-down").toggleClass("fa-caret-up");var b=[];$.each($(".draggable-group"),function(a,c){$(c).find(".toggle-button-group");a=$(c).hasClass("minimized");b.push($(c).attr("id")+"="+a)});$.cookie("group_order",b.join())})});$(".close-panel").on("click",function(){$(this).parent().parent().hide()});
$("button").tooltip();$(".toggle-button-group").tooltip()});var cleanMap=function(){document.getElementById("OSMLayer")};
