function updateZoomSpeedFilter(a){zoomFactor=a}function updateCameraFOVFilter(a){camera.setFov(a)}function updateBrushSizeFilter(){updateVars();CUnitCluster.traverse(function(a){a instanceof CUnit&&(mustExtrude?a.setCunitSize(dimensionX*BRUSH_SIZE,a.getScalePerWeight(),dimensionZ*BRUSH_SIZE):a.setCunitSize(dimensionX*BRUSH_SIZE,dimensionY*BRUSH_SIZE,dimensionZ*BRUSH_SIZE))})}
function updateSceneFilters(){resetScene();updateVars();CUnitCluster.traverse(function(a){a instanceof CUnit&&(a.getTimeStep()>=timeStepLowerBound&&a.getTimeStep()<timeStepUpperBound&&a.getCellY()>=xLowerBound&&a.getCellY()<xUpperBound&&a.getCellX()>=yLowerBound&&a.getCellX()<yUpperBound&&a.getZScore()>=zScoreLowerBound&&a.getZScore()<zScoreUpperBound?a.getMesh().visible=!0:a.getMesh().visible=!1)})}
function updateMapLayerDisplay(a){updateVars();CUnitCluster.traverse(function(b){b instanceof CUnit&&(a?(b.getMesh().position.z=-(b.getCellX()-yLowerBound)*dimensionX-offsetZ,b.getMesh().position.x=(b.getCellY()-xLowerBound)*dimensionZ-offsetX):(b.getMesh().position.z=-b.getCellX()*dimensionX-offsetZ,b.getMesh().position.x=b.getCellY()*dimensionZ-offsetX),mustExtrude?b.getMesh().position.y=(b.getScalePerWeight()-sizeTime)/2:b.getMesh().position.y=(b.getTimeStep()-timeStepLowerBound)*dimensionY-offsetY,
updateBrushSizeFilter(),b.getCellX()===yLowerBound&&(newLngMin=b.getLongitude()),b.getCellX()===yUpperBound&&(newLngMax=b.getLongitude()),b.getCellY()===xLowerBound&&(newLatMin=b.getLatitude()),b.getCellY()===xUpperBound&&(newLatMax=b.getLatitude()))});if(a){var c=encodeURIComponent(newLngMin+","+newLatMin+","+newLngMax+","+newLatMax);redrawDynamicGridHelper(baseOXYGridHelper,sizeLat,sizeLng,newSizeX,newSizeZ);redrawDynamicGridHelper(baseOYZGridHelper,sizeLng,sizeTime,newSizeZ,newSizeY);redrawDynamicGridHelper(baseOXZGridHelper,
sizeLat,sizeTime,newSizeX,newSizeY);dimensionX=sizeLat/newSizeX;dimensionY=sizeTime/newSizeY;dimensionZ=sizeLng/newSizeZ;updateBrushSizeFilter()}else c=encodeURIComponent(LNG_MIN+","+LAT_MIN+","+LNG_MAX+","+LAT_MAX),resetScene();c="https://www.openstreetmap.org/export/embed.html?bbox=LOCATION&amp;layers=MAPTYPE".replace("LOCATION",c).replace("MAPTYPE",maptype);document.getElementById("OSMLayer").setAttribute("src",c)}
function updateOneLayerFilter(){resetScene();updateVars();CUnitCluster.traverse(function(a){a instanceof CUnit&&(a.getTimeStep()===extrudeLayer&&a.getTimeStep()>=timeStepLowerBound&&a.getTimeStep()<timeStepUpperBound&&a.getCellY()>=xLowerBound&&a.getCellY()<xUpperBound&&a.getCellX()>=yLowerBound&&a.getCellX()<yUpperBound&&a.getZScore()>=zScoreLowerBound&&a.getZScore()<zScoreUpperBound?(a.getMesh().visible=!0,mustExtrude?a.getMesh().position.y=(a.getScalePerWeight()-sizeTime)/2:a.getMesh().position.y=
(a.getTimeStep()-timeStepLowerBound)*dimensionY-offsetY,updateBrushSizeFilter()):a.getMesh().visible=!1)})}function updateMapAlphaFilter(a){mapMesh.material.opacity=a;document.getElementById("outerOSM").style.opacity=a}function updateGeometryFilter(a){CUnitCluster.traverse(function(c){c instanceof CUnit&&c.changeGeometry(a)})}
function updateDynamicMapFilter(a){a?(mapMesh.visible=!0,document.getElementById("OSMLayer").style.display="none"):(mapMesh.visible=!1,document.getElementById("OSMLayer").style.display="block")}function updateInteractiveMapFilter(a){a?document.getElementById("OSMLayerBlocker").style.display="none":document.getElementById("OSMLayerBlocker").style.display="block"}function updateMapScaleXFilter(a){mapLayer.scale.x=a}function updateMapScaleYFilter(a){mapLayer.scale.y=a}
function updateMapOffsetX(a){mapLayer.position.x=baseOXYGridHelper.position.x+a}function updateMapOffsetZ(a){mapLayer.position.z=baseOXYGridHelper.position.z+a}function updateMapOffsetY(a){mapLayer.position.y=baseOXYGridHelper.position.y+a}function updateMapLayerType(a){};
