function updateZoomSpeedFilter(a){zoomFactor=a}function updateCameraFOVFilter(a){camera.setFov(a)}function updateBrushSizeFilter(){updateVars();CUnitCluster.traverse(function(a){a instanceof CUnit&&(mustExtrude?a.setCunitSize(dimensionX*BRUSH_SIZE,.5*a.getScalePerWeight(),dimensionZ*BRUSH_SIZE):a.setCunitSize(dimensionX*BRUSH_SIZE,dimensionY*BRUSH_SIZE,dimensionZ*BRUSH_SIZE))})}
function updateSceneFilters(){resetScene();updateVars();CUnitCluster.traverse(function(a){a instanceof CUnit&&(a.getTimeStep()>=timeStepLowerBound&&a.getTimeStep()<timeStepUpperBound&&a.getCellY()>=xLowerBound&&a.getCellY()<xUpperBound&&a.getCellX()>=yLowerBound&&a.getCellX()<yUpperBound&&a.getZScore()>=zScoreLowerBound&&a.getZScore()<zScoreUpperBound?a.getMesh().visible=!0:a.getMesh().visible=!1)})}
function updateMapLayerDisplay(a){updateVars();a?(CUnitCluster.traverse(function(a){if(a instanceof CUnit){a.getMesh().position.z=-(a.getCellX()-yLowerBound)*dimensionX-offsetZ;a.getMesh().position.x=(a.getCellY()-xLowerBound)*dimensionZ-offsetX;if(mustExtrude){var b=a.getScalePerWefight();a.getMesh().scale.y=b;a.getMesh().position.y=(a.getTimeStep()-timeStepLowerBound)*dimensionY-offsetY+b/2-sizeTime/2}else a.getMesh().position.y=(a.getTimeStep()-timeStepLowerBound)*dimensionY-offsetY;a.getCellX()===
yLowerBound&&(newLngMin=a.getLongitude());a.getCellX()===yUpperBound&&(newLngMax=a.getLongitude());a.getCellY()===xLowerBound&&(newLatMin=a.getLatitude());a.getCellY()===xUpperBound&&(newLatMax=a.getLatitude())}}),a=encodeURIComponent(newLngMin+","+newLatMin+","+newLngMax+","+newLatMax),redrawDynamicGridHelper(baseOXYGridHelper,sizeLat,sizeLng,newSizeX,newSizeZ),redrawDynamicGridHelper(baseOYZGridHelper,sizeLng,sizeTime,newSizeZ,newSizeY),redrawDynamicGridHelper(baseOXZGridHelper,sizeLat,sizeTime,
newSizeX,newSizeY),dimensionX=sizeLat/newSizeX,dimensionY=sizeTime/newSizeY,dimensionZ=sizeLng/newSizeZ,updateBrushSizeFilter()):(a=encodeURIComponent(LNG_MIN+","+LAT_MIN+","+LNG_MAX+","+LAT_MAX),resetScene());a="http://www.openstreetmap.org/export/embed.html?bbox=LOCATION&amp;layers=MAPTYPE&amp;marker=MRKERS".replace("LOCATION",a).replace("MAPTYPE",maptype);document.getElementById("OSMLayer").setAttribute("src",a)}
function updateOneLayerFilter(){resetScene();updateVars();CUnitCluster.traverse(function(a){if(a instanceof CUnit)if(a.getTimeStep()===extrudeLayer&&a.getTimeStep()>=timeStepLowerBound&&a.getTimeStep()<timeStepUpperBound&&a.getCellY()>=xLowerBound&&a.getCellY()<xUpperBound&&a.getCellX()>=yLowerBound&&a.getCellX()<yUpperBound&&a.getZScore()>=zScoreLowerBound&&a.getZScore()<zScoreUpperBound){if(a.getMesh().visible=!0,mustExtrude){var b=a.getScalePerWeight();a.getMesh().scale.y=b;a.getMesh().position.y=
(a.getTimeStep()-timeStepLowerBound)*dimensionY-offsetY+b/2-sizeTime/2}}else a.getMesh().visible=!1})}function updateMapAlphaFilter(a){mapMesh.material.opacity=a;document.getElementById("outerOSM").style.opacity=a}function updateGeometryFilter(a){CUnitCluster.traverse(function(b){b instanceof CUnit&&b.changeGeometry(a)})}
function updateDynamicMapFilter(a){a?(mapMesh.visible=!0,document.getElementById("OSMLayer").style.display="none"):(mapMesh.visible=!1,document.getElementById("OSMLayer").style.display="block")}function updateInteractiveMapFilter(a){a?document.getElementById("OSMLayerBlocker").style.display="none":document.getElementById("OSMLayerBlocker").style.display="block"}function updateMapScaleXFilter(a){mapLayer.scale.x=a}function updateMapScaleYFilter(a){mapLayer.scale.y=a}
function updateMapOffsetX(a){mapLayer.position.x=baseOXYGridHelper.position.x+a}function updateMapOffsetZ(a){mapLayer.position.z=baseOXYGridHelper.position.z+a}function updateMapOffsetY(a){mapLayer.position.y=baseOXYGridHelper.position.y+a}function updateMapLayerType(a){};
