var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
function makeTextSprite(a,b){void 0===b&&(b={});var c=b.hasOwnProperty("fontface")?b.fontface:"Consolas",d=b.hasOwnProperty("fontsize")?b.fontsize:.25*size,e=b.hasOwnProperty("borderThickness")?b.borderThickness:4,f=b.hasOwnProperty("borderColor")?b.borderColor:{r:0,g:0,b:0,a:0};b=b.hasOwnProperty("backgroundColor")?b.backgroundColor:{r:255,g:255,b:255,a:0};var h=document.createElement("canvas"),g=h.getContext("2d");g.font=d+"px "+c;c=g.measureText(a).width;g.fillStyle="rgba("+b.r+","+b.g+","+b.b+
","+b.a+")";g.strokeStyle="rgba("+f.r+","+f.g+","+f.b+","+f.a+")";g.lineWidth=e;roundRect(g,e/2,e/2,c+e,1.4*d+e,6);g.fillStyle="rgba(0, 0, 0, 1.0)";g.fillText(a,e,d+e);a=new THREE.Texture(h);a.minFilter=THREE.LinearFilter;a.needsUpdate=!0;a=new THREE.SpriteMaterial({map:a,depthWrite:!0});a=new THREE.Sprite(a);a.scale.set(50,25,1);return a}
function roundRect(a,b,c,d,e,f){a.beginPath();a.moveTo(b+f,c);a.lineTo(b+d-f,c);a.quadraticCurveTo(b+d,c,b+d,c+f);a.lineTo(b+d,c+e-f);a.quadraticCurveTo(b+d,c+e,b+d-f,c+e);a.lineTo(b+f,c+e);a.quadraticCurveTo(b,c+e,b,c+e-f);a.lineTo(b,c+f);a.quadraticCurveTo(b,c,b+f,c);a.closePath();a.fill();a.stroke()}function webglAvailable(){try{var a=document.createElement("canvas");return!(!window.WebGLRenderingContext||!a.getContext("webgl")&&!a.getContext("experimental-webgl"))}catch(b){return!1}}
function setOrthographic(){isInPerspectiveMode=!1;camera=combinedCamera;resetLabel();camera.toOrthographic();camera.setZoom(5);zoomAmount=5;document.getElementById("fov").innerHTML="Orthographic mode"}
function setPerspective(){isInPerspectiveMode=!0;camera=perspectiveCamera;updateMapScaleXFilter(.582245);updateMapScaleYFilter(.561175);updateMapOffsetX(-1);updateMapOffsetZ(0);resetLabel();camera.setZoom(5);zoomAmount=5;camera.position.copy(CAMERA_SPAWN);document.getElementById("fov").innerHTML="Perspective mode"}
function switchFrontCamera(){resetLabel();camera.position.x=Math.cos(2*Math.PI)*sizeLng;camera.position.z=Math.sin(2*Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGLScene.position);camera.updateProjectionMatrix();document.getElementById("fov").innerHTML="Orthographic mode: Longitude/Timestep";labelLat.visible=!1}
function switchBackCamera(){resetLabel();camera.position.x=Math.cos(Math.PI)*sizeLng;camera.position.z=Math.sin(Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLat.visible=!1;document.getElementById("fov").innerHTML="Orthographic mode: Longitude / Timestep"}
function switchLeftCamera(){resetLabel();camera.position.x=Math.cos(1.5*Math.PI)*sizeLng;camera.position.z=Math.sin(1.5*Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLng.visible=!1;labelOrigin.position.x-=35;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Timestep"}
function switchRightCamera(){resetLabel();camera.position.x=Math.cos(Math.PI/2)*sizeLng;camera.position.z=Math.sin(Math.PI/2)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLng.visible=!1;labelOrigin.position.x+=20;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Timestep"}
function switchTopCamera(){resetLabel();camera.position.x=0;camera.position.z=Math.sin(2*Math.PI)*sizeLat;camera.position.y=Math.cos(2*Math.PI)*sizeTime;camera.lookAt(WebGLScene.position);camera.updateProjectionMatrix();labelT.visible=!1;labelLng.position.z+=10;labelLng.position.x-=30;labelLat.position.x-=50;labelOrigin.position.x-=30;document.getElementById("fov").innerHTML="Orthographic mode: Longitude / Latitude";updateMapScaleXFilter(.522);updateMapScaleYFilter(.505);updateMapOffsetX(-1);updateMapOffsetZ(0)}
function switchBottomCamera(){resetLabel();camera.position.x=0;camera.position.z=Math.sin(Math.PI)*sizeLat;camera.position.y=Math.cos(Math.PI)*sizeTime;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelT.visible=!1;labelLng.position.z+=20;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Longitude"}
function resetLabel(){labelLat.visible=!0;labelLat.position.copy(LABEL_LAT_SPAWN);labelOrigin.visible=!0;labelOrigin.position.copy(LABEL_ORIGIN_SPAWN);labelT.visible=!0;labelT.position.copy(LABEL_TIME_SPAWN);labelLng.visible=!0;labelLng.position.copy(LABEL_LNG_SPAWN)}function resetScene(){CUnitCluster.traverse(function(a){a instanceof CUnit&&a.reinitiate()})}
function createCSS3DObject(a){var b=document.createElement("div");b.innerHTML=a;b.style.opacity=.7;b.style.width="661px";b.style.height="689px";b.style.webkitTransformStyle="preserve-3d";b.style.zIndex=4;return new THREE.CSS3DObject(b)}
function createDynamicGridHelper(a,b){console.log("Scaling");var c=new THREE.Object3D;switch(a){case "OXY":b=new THREE.Geometry;b.vertices.push(new THREE.Vector3(-size/2,0,0));b.vertices.push(new THREE.Vector3(size/2,0,0));linesMaterial=new THREE.LineBasicMaterial({color:0,opacity:1,linewidth:1});for(var d=0;d<=newSizeZ;d++)a=new THREE.Line(b,linesMaterial),a.position.z=d*sizeLng/newSizeZ-size/2,c.add(a);for(d=0;d<=newSizeX;d++)a=new THREE.Line(b,linesMaterial),a.position.x=d*sizeLat/newSizeX-size/
2,a.rotation.y=90*Math.PI/180,c.add(a);c.renderOrder=1;break;case "OYZ":baseOYZGridHelper=new THREE.GridHelper(size,b);baseOYZGridHelper.rotation.z=Math.PI/2;baseOYZGridHelper.rotation.y=Math.PI/2;baseOYZGridHelper.position.x=baseOXYGridHelper.position.x;baseOYZGridHelper.position.z=baseOXYGridHelper.position.z+sizeLng/2;baseOYZGridHelper.position.y=baseOXYGridHelper.position.y+size/2;baseOYZGridHelper.scale.z=sizeLat/size;baseOYZGridHelper.renderOrder=1;break;default:baseOXZGridHelper=new THREE.GridHelper(size,
b),baseOXZGridHelper.rotation.z=Math.PI/2,baseOXZGridHelper.position.x=baseOXYGridHelper.position.x-sizeLat/2,baseOXZGridHelper.position.z=baseOXYGridHelper.position.z,baseOXZGridHelper.position.y=baseOXYGridHelper.position.y+size/2,baseOXZGridHelper.scale.z=sizeLng/size,baseOXZGridHelper.renderOrder=1}return c};
