var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
function makeTextSprite(a,b){void 0===b&&(b={});var c=b.hasOwnProperty("fontface")?b.fontface:"Consolas",d=b.hasOwnProperty("fontsize")?b.fontsize:.25*size,e=b.hasOwnProperty("borderThickness")?b.borderThickness:4,f=b.hasOwnProperty("borderColor")?b.borderColor:{r:0,g:0,b:0,a:0};b=b.hasOwnProperty("backgroundColor")?b.backgroundColor:{r:255,g:255,b:255,a:0};var g=document.createElement("canvas"),h=g.getContext("2d");h.font=d+"px "+c;c=h.measureText(a).width;h.fillStyle="rgba("+b.r+","+b.g+","+b.b+
","+b.a+")";h.strokeStyle="rgba("+f.r+","+f.g+","+f.b+","+f.a+")";h.lineWidth=e;roundRect(h,e/2,e/2,c+e,1.4*d+e,6);h.fillStyle="rgba(0, 0, 0, 1.0)";h.fillText(a,e,d+e);a=new THREE.Texture(g);a.minFilter=THREE.LinearFilter;a.needsUpdate=!0;a=new THREE.SpriteMaterial({map:a,depthWrite:!0});a=new THREE.Sprite(a);a.scale.set(50,25,1);return a}
function roundRect(a,b,c,d,e,f){a.beginPath();a.moveTo(b+f,c);a.lineTo(b+d-f,c);a.quadraticCurveTo(b+d,c,b+d,c+f);a.lineTo(b+d,c+e-f);a.quadraticCurveTo(b+d,c+e,b+d-f,c+e);a.lineTo(b+f,c+e);a.quadraticCurveTo(b,c+e,b,c+e-f);a.lineTo(b,c+f);a.quadraticCurveTo(b,c,b+f,c);a.closePath();a.fill();a.stroke()}function webglAvailable(){try{var a=document.createElement("canvas");return!(!window.WebGLRenderingContext||!a.getContext("webgl")&&!a.getContext("experimental-webgl"))}catch(b){return!1}}
function setOrthographic(){isInPerspectiveMode=!1;camera=combinedCamera;resetLabel();camera.toOrthographic();camera.setZoom(5);zoomAmount=5;document.getElementById("fov").innerHTML="Orthographic mode"}
function setPerspective(){isInPerspectiveMode=!0;camera=perspectiveCamera;updateMapScaleXFilter(.582245*mapScaleOffsetX);updateMapScaleYFilter(.561175*mapScaleOffsetY);updateMapOffsetX(-1);updateMapOffsetZ(0);resetLabel();camera.setZoom(5);zoomAmount=5;camera.position.copy(CAMERA_SPAWN);document.getElementById("fov").innerHTML="Perspective mode"}
function switchFrontCamera(){resetLabel();camera.position.x=Math.cos(2*Math.PI)*sizeLng;camera.position.z=Math.sin(2*Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGLScene.position);camera.updateProjectionMatrix();document.getElementById("fov").innerHTML="Orthographic mode: Longitude/Timestep";labelLat.visible=!1}
function switchBackCamera(){resetLabel();camera.position.x=Math.cos(Math.PI)*sizeLng;camera.position.z=Math.sin(Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLat.visible=!1;document.getElementById("fov").innerHTML="Orthographic mode: Longitude / Timestep"}
function switchLeftCamera(){resetLabel();camera.position.x=Math.cos(1.5*Math.PI)*sizeLng;camera.position.z=Math.sin(1.5*Math.PI)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLng.visible=!1;labelOrigin.position.x-=35;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Timestep"}
function switchRightCamera(){resetLabel();camera.position.x=Math.cos(Math.PI/2)*sizeLng;camera.position.z=Math.sin(Math.PI/2)*sizeLat;camera.position.y=0;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelLng.visible=!1;labelOrigin.position.x+=20;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Timestep"}
function switchTopCamera(){resetLabel();camera.position.x=0;console.log(THREE.Math.radToDeg(camera.position.x));camera.position.z=Math.sin(2*Math.PI)*sizeLat;camera.position.y=Math.cos(2*Math.PI)*sizeTime;camera.lookAt(WebGLScene.position);camera.updateProjectionMatrix();labelT.visible=!1;labelLng.position.z+=10;labelLng.position.x-=30;labelLat.position.x-=50;labelOrigin.position.x-=30;document.getElementById("fov").innerHTML="Orthographic mode: Longitude / Latitude";updateMapScaleXFilter(.522*mapScaleOffsetX);
updateMapScaleYFilter(.505*mapScaleOffsetY);updateMapOffsetX(-1);updateMapOffsetZ(0)}function switchBottomCamera(){resetLabel();camera.position.x=0;camera.position.z=Math.sin(Math.PI)*sizeLat;camera.position.y=Math.cos(Math.PI)*sizeTime;camera.lookAt(WebGlScene.position);camera.updateProjectionMatrix();labelT.visible=!1;labelLng.position.z+=20;document.getElementById("fov").innerHTML="Orthographic mode: Latitude / Longitude"}
function resetLabel(){labelLat.visible=!0;labelLat.position.copy(LABEL_LAT_SPAWN);labelOrigin.visible=!0;labelOrigin.position.copy(LABEL_ORIGIN_SPAWN);labelT.visible=!0;labelT.position.copy(LABEL_TIME_SPAWN);labelLng.visible=!0;labelLng.position.copy(LABEL_LNG_SPAWN)}function resetScene(){CUnitCluster.traverse(function(a){a instanceof CUnit&&a.reinitiate()})}
function createCSS3DObject(a){var b=document.createElement("div");b.innerHTML=a;b.style.opacity=.7;b.style.width="661px";b.style.height="689px";b.style.webkitTransformStyle="preserve-3d";b.style.zIndex=-1;a=new THREE.CSS3DObject(b);a.renderOrder=4;return a}
function createDynamicGridHelper(a,b,c,d){for(var e=new THREE.Geometry,f=new THREE.LineBasicMaterial({color:0,opacity:.7}),g=-a/2;g<=a/2;g+=a/c)e.vertices.push(new THREE.Vector3(-b/2,0,g)),e.vertices.push(new THREE.Vector3(b/2,0,g));for(g=-b/2;g<=b/2;g+=b/d)e.vertices.push(new THREE.Vector3(g,0,-a/2)),e.vertices.push(new THREE.Vector3(g,0,a/2));a=new THREE.Line(e,f,THREE.LinePieces);a.renderOrder=1;WebGLScene.add(a);return a}
function redrawDynamicGridHelper(a,b,c,d,e){for(var f=new THREE.Geometry,g=-b/2;g<=b/2;g+=b/d)f.vertices.push(new THREE.Vector3(-c/2,0,g)),f.vertices.push(new THREE.Vector3(c/2,0,g));for(g=-c/2;g<=c/2;g+=c/e)f.vertices.push(new THREE.Vector3(g,0,-b/2)),f.vertices.push(new THREE.Vector3(g,0,b/2));a instanceof THREE.Line&&(a.geometry=f)}
function updateVars(){dimensionX=sizeLat/newSizeX;dimensionY=sizeTime/newSizeY;dimensionZ=sizeLng/newSizeZ;offsetZ=(-sizeLat+dimensionX)/2;offsetX=(sizeLng-dimensionZ)/2;offsetY=(sizeTime-dimensionY)/2}
function updateChunksVars(){TIME_STEP_LOWER_BOUND=dataChunks[selectedChunk][0].time_step;TIME_STEP_UPPER_BOUND=dataChunks[selectedChunk][dataChunks[selectedChunk].length-1].time_step;ZSCORE_LOWER_BOUND=dataChunks[selectedChunk][0].zscore;ZSCORE_UPPER_BOUND=dataChunks[selectedChunk][dataChunks[selectedChunk].length-1].zscore;X_LOWER_BOUND=dataChunks[selectedChunk][0].cell_x;X_UPPER_BOUND=dataChunks[selectedChunk][dataChunks[selectedChunk].length-1].cell_x;Y_LOWER_BOUND=dataChunks[selectedChunk][0].cell_y;
Y_UPPER_BOUND=dataChunks[selectedChunk][dataChunks[selectedChunk].length-1].cell_y;for(var a=$jscomp.makeIterator(dataChunks[selectedChunk]),b=a.next();!b.done;b=a.next())b=b.value,b.time_step<TIME_STEP_LOWER_BOUND&&(TIME_STEP_LOWER_BOUND=b.time_step),b.time_step>TIME_STEP_UPPER_BOUND&&(TIME_STEP_UPPER_BOUND=b.time_step),b.zscore<ZSCORE_LOWER_BOUND&&(ZSCORE_LOWER_BOUND=b.zscore),b.zscore>ZSCORE_UPPER_BOUND&&(ZSCORE_UPPER_BOUND=b.zscore),b.cell_x<X_LOWER_BOUND&&(X_LOWER_BOUND=b.cell_x),b.cell_x>X_UPPER_BOUND&&
(X_UPPER_BOUND=b.cell_x),b.cell_y<Y_LOWER_BOUND&&(Y_LOWER_BOUND=b.cell_y),b.cell_y>Y_UPPER_BOUND&&(X_UPPER_BOUND=b.cell_y);document.getElementById("chunk_details").innerHTML="<h3><strong>Chunk #"+selectedChunk+"</strong></h3><p>"+("<strong>Time_step:</strong> "+TIME_STEP_LOWER_BOUND+" - "+TIME_STEP_UPPER_BOUND+"<br/>")+("<strong>zScore:</strong> "+ZSCORE_LOWER_BOUND+" - "+ZSCORE_UPPER_BOUND+"<br/>")+("<strong>cell_x:</strong> "+X_LOWER_BOUND+" - "+X_UPPER_BOUND+"<br/>")+("<strong>cell_y:</strong> "+
Y_LOWER_BOUND+" - "+Y_UPPER_BOUND+"<br/>")+"</p>";timeStepLowerBound=TIME_STEP_LOWER_BOUND;timeStepUpperBound=TIME_STEP_UPPER_BOUND;zScoreLowerBound=ZSCORE_LOWER_BOUND;zScoreUpperBound=ZSCORE_UPPER_BOUND;xLowerBound=X_LOWER_BOUND;xUpperBound=X_UPPER_BOUND;yLowerBound=Y_LOWER_BOUND;yUpperBound=Y_UPPER_BOUND;ZSCORE_SCALE=ZSCORE_UPPER_BOUND-ZSCORE_LOWER_BOUND}function getTimeStampFromStep(a){return new Date(TIME_GENESIS.getTime()+72E5*a)}
function getLatitudePoint(a,b){a=LAT_MIN+a*CELL_DISTANCE_LAT/LENGTH_DEG_LAT*(LAT_MAX-LAT_MIN);return b?THREE.Math.degToRad(a):a}function getLongitudePoint(a,b){a=LNG_MIN+a*CELL_DISTANCE_LNG*(LNG_MAX-LNG_MIN)/LENGTH_DEG_LNG;return b?THREE.Math.degToRad(a):a}
function getDistanceBetweenCoordinates(a,b,c,d){var e=THREE.Math.degToRad(a),f=THREE.Math.degToRad(b);a=THREE.Math.degToRad(b-a);c=THREE.Math.degToRad(d-c);e=Math.sin(a/2)*Math.sin(a/2)+Math.cos(e)*Math.cos(f)*Math.sin(c/2)*Math.sin(c/2);return 12742E3*Math.atan2(Math.sqrt(e),Math.sqrt(1-e))}function getAngleDistance(a,b){return Math.sqrt(Math.pow(a*CELL_DISTANCE_LAT,2)+Math.pow(b*CELL_DISTANCE_LAT,2))/6371}
function clearScene(){CUnitCluster.traverse(function(a){a instanceof CUnit&&WebGLScene.remove(a.getMesh())});CUnitCluster=new THREE.Object3D}
function reloadData(){processedData&&dataChunks&&0<processedData.length&&0<dataChunks.length&&(processedData=[]);dataChunks=[];selectedChunk=0;CSVLoader.setResponseType("text");CSVLoader.load("./data/"+fileName+".minified.json",function(a){processedData=JSON.parse(a);processedData.sort(function(a,b){return a.time_step-b.time_step});a=0;for(var b=processedData.length;a<b;a+=chunkSize){var c=processedData.slice(a,a+chunkSize);dataChunks.push(c)}document.getElementById("chunk_info").innerHTML=dataChunks.length+
" chunks | "+processedData.length+" entries";rebuildUI()})};
