var size=300,sizeLng=311,sizeTime=size,sizeLat=245,newSizeZ=sizeLng,newSizeY=sizeTime,newSizeX=sizeLat,step=50,mapScaleOffsetX=sizeLng/237,mapScaleOffsetY=sizeLat/235,dataChunks=[],selectedChunk=0,fileName="gistar_output_b",TIME_GENESIS=new Date(2015,0,1,0,0,0);console.log(TIME_GENESIS.toDateString());
var TIME_STEP_LOWER_BOUND,TIME_STEP_UPPER_BOUND,ZSCORE_LOWER_BOUND,ZSCORE_UPPER_BOUND,ZSCORE_SCALE,X_LOWER_BOUND,X_UPPER_BOUND,Y_LOWER_BOUND,Y_UPPER_BOUND,xLowerBound,xUpperBound,yLowerBound,yUpperBound,timeStepLowerBound,timeStepUpperBound,zScoreLowerBound,zScoreUpperBound,CSVLoader=new THREE.FileLoader;CSVLoader.setResponseType("text");
CSVLoader.load("./data/"+fileName+".minified.json",function(a){a=JSON.parse(a);a.sort(function(a,b){return a.time_step-b.time_step});for(var b=0,c=a.length;b<c;b+=1E3){var d=a.slice(b,b+1E3);dataChunks.push(d)}console.log(dataChunks.length+" data chunks from "+a.length+" data processed");rebuildUI()});
var stats,camera,controls,WebGLRenderer,cssRenderer,WebGLScene=new THREE.Scene,cssScene=new THREE.Scene,raycaster=new THREE.Raycaster,mouse=new THREE.Vector2,INTERSECTED,CUnitCluster=new THREE.Object3D,zoomAmount=1,zoomFactor=5,isLMB=!1,isRMB=!1,dimensionX=sizeLat/newSizeX,dimensionY=sizeTime/newSizeY,dimensionZ=sizeLng/newSizeZ,offsetZ=(-sizeLat+dimensionX)/2,offsetX=(sizeLng-dimensionZ)/2,offsetY=(sizeTime-dimensionY)/2,mapMesh,mapMat,mapLayer,extrudeLayer=-1,mustExtrude=!1,mustScale=!1,baseOXYGridHelper=
createDynamicGridHelper(sizeLat,sizeLng,newSizeX,newSizeZ);baseOXYGridHelper.position.z=0;baseOXYGridHelper.position.x=0;baseOXYGridHelper.position.y=-sizeTime/2;var baseOYZGridHelper=createDynamicGridHelper(sizeLng,sizeTime,newSizeZ,newSizeY);baseOYZGridHelper.rotation.z=Math.PI/2;baseOYZGridHelper.rotation.y=Math.PI/2;baseOYZGridHelper.position.x=baseOXYGridHelper.position.x;baseOYZGridHelper.position.z=baseOXYGridHelper.position.z+sizeLat/2;
baseOYZGridHelper.position.y=baseOXYGridHelper.position.y+sizeTime/2;var baseOXZGridHelper=createDynamicGridHelper(sizeLat,sizeTime,newSizeX,newSizeY);baseOXZGridHelper.rotation.z=Math.PI/2;baseOXZGridHelper.position.x=baseOXYGridHelper.position.x-sizeLng/2;baseOXZGridHelper.position.z=baseOXYGridHelper.position.z;baseOXZGridHelper.position.y=baseOXYGridHelper.position.y+sizeTime/2;
var GEO_PRISM=new THREE.CylinderGeometry(dimensionX,dimensionZ,dimensionY,6,4),GEO_CUBE=new THREE.BoxGeometry(dimensionX,dimensionY,dimensionZ),BRUSH_SIZE=1,CAMERA_SPAWN=new THREE.Vector3(size,size,size),LABEL_ORIGIN_SPAWN=new THREE.Vector3(baseOXYGridHelper.position.x-(size-sizeLng/2),baseOXYGridHelper.position.y,baseOXYGridHelper.position.z+(size-sizeLat/2)),LABEL_TIME_SPAWN=new THREE.Vector3(baseOXZGridHelper.position.x,baseOXZGridHelper.position.y+(size-sizeTime/2),baseOXZGridHelper.position.z+
(size-sizeLat/2)),LABEL_LAT_SPAWN=new THREE.Vector3(baseOXYGridHelper.position.x-(size-sizeLng/2),baseOXYGridHelper.position.y-.1*size,-baseOXYGridHelper.position.z-(size-sizeLat/2)),LABEL_LNG_SPAWN=new THREE.Vector3(baseOXYGridHelper.position.x+(size-sizeLng/2),baseOXYGridHelper.position.y-.1*size,baseOXYGridHelper.position.z+(size-sizeLat/2)),labelOrigin,labelT,labelLng,labelLat,zoom=13,LNG_MIN=-74.25909,LNG_MAX=-73.70009,LAT_MIN=40.477399,LAT_MAX=40.917577,newLngMin=LNG_MIN,newLatMin=LAT_MIN,newLngMax=
LNG_MAX,newLatMax=LAT_MAX,LENGTH_DEG_LAT=getDistanceBetweenCoordinates(LAT_MIN,LAT_MAX,LNG_MIN,LNG_MIN),LENGTH_DEG_LNG=getDistanceBetweenCoordinates(LAT_MIN,LAT_MIN,LNG_MIN,LNG_MAX),CELL_DISTANCE_LAT=LENGTH_DEG_LAT/sizeLat,CELL_DISTANCE_LNG=LENGTH_DEG_LNG/sizeLng;console.log(CELL_DISTANCE_LAT);console.log(CELL_DISTANCE_LNG);
var loc=encodeURIComponent(LNG_MIN+","+LAT_MIN+","+LNG_MAX+","+LAT_MAX),OSMFrame='<div id="outerOSM" style="opacity: 1"><div id="innerOSM"><div id="OSMLayerBlocker" style="position:fixed;width:100%;height:100%;"></div><iframe id="OSMLayer" width="661px" height="689px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.openstreetmap.org/export/embed.html?bbox=LOCATION&amp;layers=MAPTYPE" style="border: 1px solid black"></iframe></div></div>',mapoption="",maptype="mapnik"+
mapoption,markers=encodeURIComponent(LAT_MIN+","+LNG_MIN),sides=[],isInPerspectiveMode=!0,combinedCamera=new THREE.CombinedCamera(window.innerWidth,window.innerHeight,90,1,1E3,-500,1E3);combinedCamera.isPerspectiveCamera=!0;combinedCamera.isOrthographicCamera=!1;combinedCamera.position.copy(CAMERA_SPAWN);combinedCamera.lookAt(new THREE.Vector3(sizeLng/2,sizeTime/2,sizeLat/2));var perspectiveCamera=new THREE.PerspectiveCamera(50,window.innerWidth/window.innerHeight,1,5E3);
perspectiveCamera.position.set(500,350,750);
